name: React / Node.js CI Build and Docker Publish to ECR

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Docker Build and Publish to ECR
        env:
          AWS_REGION: ap-south-1
          AWS_ACCOUNT_ID: 851725578916
          ECR_REPO: pocregistry
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:nodejs-latest .
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:nodejs-latest
